version: '2'
services:
  junebug:
      build: .
      ports:
       - "8080:8080"
      links:
       - redis
       - rabbitmq
      environment:
       REDIS_HOST: 'redis'
       REDIS_PORT: '6379'
       AMQP_HOST: 'rabbitmq'
       AMQP_PORT: '5672'
  redis:
      image: redis
  rabbitmq:
      image: rabbitmq
      environment:
        RABBITMQ_DEFAULT_VHOST: '/guest'
